28 refactor redesign package structure on backend according to clean code principles in java spring
SWE574-G3/SWE-574-G3 pull request #30
Opened 2024-10-16 19:55 UTC by Ozmus

Folder structure is refactored. Controller, service, repository, model, validator, dto, response, and key packages are created and related files are moved to the packages. Auth and exception packages are remained yet refactored.

2024-10-20 12:57 UTC, niloaydin approved these changes

2024-10-20 13:06 UTC, niloaydin requested changes

2024-10-20 13:06 UTC, niloaydin commented on Communitter/src/main/java/com/communitter/api/validator/PostValidator.java
Can we change the name to utils, so we can add additional functions inside one folder instead of creating individual folders

2024-10-21 19:58 UTC, Ozmus commented on Communitter/src/main/java/com/communitter/api/validator/PostValidator.java
done

2024-10-21 20:15 UTC, ynsmrkrkmz approved these changes

2024-10-22 12:39 UTC, Oguzoz1 approved these changes
Demands has been accomplished.

2024-10-22 14:45 UTC, niloaydin approved these changes

2024-10-22 15:02 UTC, CankutER approved these changes

2024-10-22 15:03 UTC, AhmetZ06 approved these changes

2024-10-23 08:35 UTC, merged